Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/add_user'
  get 'admin/user_list'
  get 'admin/profile'
  get 'admin/post'
  get 'admin/post_list'
  get 'blog/index'
  get 'blog/blog_single'
  root 'home#index'
  get 'home/about'
  get 'home/contact'
  get 'home/faqs'
  get 'home/why_choose_us'
  get 'home/blog'
  get 'home/testimonials'
  get 'home/our_history'
  get 'home/services'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
